<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ISMA.Domain\ISMA.Domain.csproj" />
    <ProjectReference Include="..\..\src\ISMA.ViewModels\ISMA.ViewModels.csproj" />
    <ProjectReference Include="..\..\src\ISMA.App\ISMA.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
  </ItemGroup>

</Project>
