<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ISMA.Domain\ISMA.Domain.csproj" />
    <ProjectReference Include="..\ISMA.Grpc\ISMA.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.Client.Web" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
