global using global::Xunit;
global using FluentAssertions;
global using ISMA.Domain.Contracts;
global using ISMA.Domain.Dtos;
global using ISMA.Domain.Models;
global using ISMA.Tests.Integration;
global using ISMA.ViewModels.Services;
global using ISMA.ViewModels.ViewModels;
global using Microsoft.Extensions.DependencyInjection;
