<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="v1/**/*.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
